### ISSUE TITLE
Exception in thread Thread-2

### ISSUE THREAD

**Issue by linetrimmer** [hrfee/jellyfin-accounts#9] opened 2020-04-16 12:44 UTC
Running in Docker, every so often I'll get this in the logs after I try to request a password reset through Jellyfin. After this happens, the container needs to be manually reset before it'll try doing anything else. It usually ends up working the next time after deleting the .json -> restarting the container -> requesting a password reset again.

Exception in thread Thread-2:

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner

    self.run()

  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/api.py", line 196, in run

    self.dispatch_events(self.event_queue, self.timeout)

  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/api.py", line 369, in dispatch_events

    handler.dispatch(event)

  File "/usr/local/lib/python3.8/site-packages/watchdog/events.py", line 330, in dispatch

    self.on_any_event(event)

  File "/usr/local/lib/python3.8/site-packages/jellyfin_accounts-0.1-py3.8.egg/jellyfin_accounts/pw_reset.py", line 172, in on_any_event

    reset = json.load(f)

  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load

    return loads(fp.read(),

  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads

    return _default_decoder.decode(s)

  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by linetrimmer** [comment] 2020-04-16 13:01
Also just a sidenote about the timezone setting since it took me a bit to figure this out: in the password reset email, the time that it says the pin code expires is coming from the jellyfin container, so that has to have the correct timezone too.

**Comment by hrfee** [comment] 2020-04-16 13:04
It's difficult to really tell why this is, but the main culprits are that for some reason its reading a different, non-json file instead of passwordreset*.json, or that it's reading the file before Jellyfin has actually finished writing the file. I've added an extra debug message (`Password reset file: /path/to/file`) and changed when the code actually triggers. The new docker image is currently building, So if you could wait until its up on docker hub, try running that (with debug set as true in the config), and send me the necessary parts of the log, we'll hopefully be able to see what the issue is.

**Comment by hrfee** [comment] 2020-04-16 13:05
Oh and I remember having the same timezone problem with my jellyfin container too, I forgot to mention it on here. I'll add that now.

**Comment by hrfee** [comment] 2020-04-23 23:09
Is this working now? I'd like to close the issue.

**Closed as completed** 2020-05-03 17:48 UTC
